@startuml github.weichware10.analyse.gui
title github.weichware10.analyse.gui

package github.weichware10.analyse.gui {

    package github.weichware10.analyse.gui.admin {

        class github.weichware10.analyse.gui.admin.Configurator {
            {static}- Parent root
            {static}- ConfiguratorController controller
            {static}- List<String> strings
            {static}- boolean stringsExistInDatabase
            {static}# SimpleObjectProperty<Mode> mode
            {static}# String configId
            __public method__
            {static}+ void start()
            __private methods__
            {static}- void fillGui(Configuration configuration, Mode nextMode)
            {static}- Configuration getConfiguration()
            __protected methods__
            {static}# void loadFromJson()
            {static}# void writeToJson()
            {static}# void loadFromDataBase()
            {static}# void writeToDataBase()
            {static}# void showStringsDialog()
            {static}# Thread updateStringList(List<String> newStr)
            {static}# void changeToEdit()
        }
        enum github.weichware10.analyse.gui.admin.ConfiguratorMode {
            JSONVIEW
            JSONEDIT
            DBVIEW
            DBEDIT
            NEW 
        }
        github.weichware10.analyse.gui.admin.Configurator +-- github.weichware10.analyse.gui.admin.ConfiguratorMode

        class github.weichware10.analyse.gui.admin.ConfiguratorController {
            - ResourceBundle resources
            - URL location
            # GridPane codeChartsConfigPane
            # Label configHeading
            # Label configSubHeading
            # Button dataBaseSaveButton
            # TextField horizontalSplitField
            # TextField imageViewHeightField
            # TextField imageViewWidthField
            # TextField imgUrlField
            # TextField initialSizeFieldX
            # TextField initialSizeFieldY
            # TextField introField
            # TextField iterationsField
            # Button jsonSaveButton
            # TextField maxDepthField
            # TextField outroField
            # CheckBox randomStringsBox
            # CheckBox relativeSizeBox
            # CheckBox showGridBox
            # TextField speedField
            # Button stringIdButton
            # TextField stringIdField
            # TextField timingsGridField
            # TextField timingsImgField
            # ComboBox<ToolType> toolTypeBox
            # CheckBox tutorialBox
            # TextField verticalSplitField
            # TextField questionField
            # GridPane zoomMapsConfigPane
            # TextArea problemArea
            # TextField configIdField
            __private methods__
            - void startFunctionChooser()
            - void loadFromJson()
            - void writeToJson()
            - void loadFromDataBase()
            - void writeToDataBase()
            - void showStringsDialog()
            - void checkInt(ActionEvent event)
            - void checkInt(TextField intField, boolean force)
            - void checkDouble(ActionEvent event)
            - void checkDouble(TextField doubleField, boolean force)
            - void setConfigType()
            - void setTitle()
            - void reset()
            __protected method__
            # void initialize()
        }

        class github.weichware10.analyse.gui.admin.StringsDialog {
            - BorderPane root
            - StringsDialogController controller
            __public method__
            +  StringsDialog(List<String> strings, boolean editable)
            __private method__
            - List<String> convertResult(ButtonType buttonType)
        }

        class github.weichware10.analyse.gui.admin.StringsDialogController {
            - ResourceBundle resources
            - URL location
            - Label countLabel
            # TextArea stringsArea
            # Label titleLabel
            # List<String> strings
            __private method__
            - void updateStrings()
            __protected method__
            # void initialize()
        }

        class github.weichware10.analyse.gui.admin.TrialCreator {
            {static}- Parent root
            {static}- TrialCreatorController controller
            {static}# Runnable configAvailabiltyChecker
            __public method__
            {static}+ void start()
            __protected methods__
            {static}# void createTrials()
            {static}# void saveToTxt()
        }

        class github.weichware10.analyse.gui.admin.TrialCreatorController {
            - ResourceBundle resources
            - URL location
            # TextField configIdField
            # ComboBox<Integer> countBox
            - Button saveButton
            # TextArea trialIdArea
            # Button trialsCreateButton
            __private methods__
            - void startFunctionChooser()
            - void createTrials()
            - void saveToTxt()
            __protected method__
            # void initialize()
        }

    }

    package github.weichware10.analyse.gui.analyse {

        class github.weichware10.analyse.gui.analyse.Analyzer {
            {static}- Parent root
            {static}- AnalyzerController controller
            {static}- AnalyseType analyseType
            {static}- TrialData trial
            {static}- TrialData trialComp
            {static}- HeatmapConfig hmConfig
            {static}- DiagramConfig diaConfig
            {static}- String heatmapImage
            {static}- LineChart<Number, Number> verlaufLineChart
            {static}- BarChart<String, Number> diagramBarChart
            {static}- PieChart diagramPieChart
            __public methods__
            {static}+ void start()
            {static}+ void setAnalyseType(AnalyseType analyseType)
            {static}+ void setTrialId()
            {static}+ void setTrialIdComp()
            {static}+ void setConfig()
            {static}+ void analyse()
            {static}+ void export()
            {static}+ void exportRaw()
            {static}+ void reset()
            __private methods__
            {static}- boolean saveImage(String location)
            {static}- boolean saveAsPng(String location)
            {static}- void exportRaw(TrialData trial)
        }

        class github.weichware10.analyse.gui.analyse.AnalyzerController {
            # Button analyseButton
            # StackPane analysePane
            # MenuButton analyseTypMenuButton
            # Button backButton
            # Button configButton
            # Label errorLabel
            # Button exportButton
            # Button exportRawButton
            - Hyperlink fileLink
            # Button selectCompTrialButton
            - HBox statusBox
            - Text statusTextLeft
            - Text statusTextRight
            - String filename
            - ProgressIndicator pi
            __protected methods__
            # void setStatus(String statusLeft, String filename, String statusRight)
            # void setStatusIndicator(boolean active)
            # void analyze(ActionEvent event)
            # void back(ActionEvent event)
            # void export(ActionEvent event)
            # void exportRaw(ActionEvent event)
            # void openFile(ActionEvent event)
            # void selectTrial(ActionEvent event)
            # void selectTrialForComp(ActionEvent event)
            # void setCompVerlauf(ActionEvent event)
            # void setConfig(ActionEvent event)
            # void setHeatmap(ActionEvent event)
            # void setRelDepthDistr(ActionEvent event)
            # void setVerlauf(ActionEvent event)
            # void initialize()
        }

        class github.weichware10.analyse.gui.analyse.DiagramConfigurator {
            {static}- VBox root
            {static}- DiagramConfiguratorController controller
            __public method__
            {static}+ void start(DiagramConfig diaConfig, AnalyseType analyseType)
        }

        class github.weichware10.analyse.gui.analyse.DiagramConfiguratorController {
            - int steps
            - RadioButton barChart
            - RadioButton pieChart
            # Slider stepsSlider
            # Label stepsLabel
            __private methods__
            - void selectBarChart(ActionEvent event)
            - void selectPieChart(ActionEvent event)
            __protected methods__
            # boolean isBarChart()
            # void setBarChart(boolean selected)
            # void setPieChart(boolean selected)
            # void initStepsSlider(int current)
            # int getSteps()
            # void initialize()
        }

        class github.weichware10.analyse.gui.analyse.HeatmapConfigurator {
            {static}- VBox root
            {static}- HeatmapConfiguratorController controller
            __public method__
            {static}+ void start(HeatmapConfig hmConfig)
        }

        class github.weichware10.analyse.gui.analyse.HeatmapConfiguratorController {
            # ColorPicker maxColorDiff
            # ColorPicker minColorDiff
            # CheckBox showImage
            __protected methods__
            # Color getMaxColorDiff()
            # Color getMinColorDiff()
            # boolean getShowImage()
            # void setMaxColorDiff(Color maxColorDiff)
            # void setMinColorDiff(Color minColorDiff)
            # void setShowImage(boolean showImage)
            # void initialize()
        }

        class github.weichware10.analyse.gui.analyse.TrialSelector {
            {static}- BorderPane root
            {static}- TrialSelectorController controller
            {static}- String trialId
            {static}- TrialData trialData
            {static}- String fixedConfigId
            {static}- Dialog<Void> selectorDialog
            {static}- Button selectButton
            __public method__
            {static}+ TrialData getTrialData(String fixedConfigId)
            __private methods__
            {static}- DateTime localDateToDateTime(java.time.LocalDate localDate, boolean endOfDay)
            {static}- BorderPane initialize()
            {static}- void selectEventFilter(ActionEvent selectEvent)
            __protected methods__
            {static}# void search()
            {static}# void searchForList()
            {static}# void searchForTrial()
            {static}# void loadFromJson(ActionEvent jsonEvent)
            {static}# void reset()
        }

        class github.weichware10.analyse.gui.analyse.TrialSelectorController {
            - int minAmount
            - int maxAmount
            - int defaultAmount
            # ComboBox<Integer> amountBox
            # TextField configIdField
            # DatePicker endPicker
            # TableView<TrialData> resultTable
            # DatePicker startPicker
            # ComboBox<ToolType> toolTypeBox
            # Button searchButton
            # Label warnLabel
            # ProgressIndicator indicator
            # TextField trialIdField
            # Label jsonLabel
            __private methods__
            - void search()
            - void reset()
            __protected methods__
            # Integer checkAmountInput()
            # void setWarn(String warn)
            # void initEndPicker()
            # void initResultTable()
            # void initAmountBox(int minAmount, int maxAmount, int defaultAmount)
            # void initAmountBox()
            # void initToolTypeBox()
            # void initialize()
        }

    }

    package github.weichware10.analyse.gui.general {
        class github.weichware10.analyse.gui.general.FunctionChooser {
            {static}- Parent root
            __public method__
            {static}+ void start()
        }

        class github.weichware10.analyse.gui.general.FunctionChooserController {
            - Button trialCreatorButton
            - Button configuratorButton
            __protected methods__
            # void initialize()
            # void logOut()
            # void startAnalyzer()
            # void startConfigurator()
            # void startTrialCreator()
        }

        class github.weichware10.analyse.gui.general.Login {
            {static}- SimpleBooleanProperty connection
            {static}+ ObservableBooleanValue hasConnection
            {static}- Parent root
            __public methods__
            {static}+ void start()
            {static}+ void logOut()
            {static}+ void connectToDatabase(String username, String password, String schema, Text warnText, TextArea errorText, ProgressIndicator indicator)
            __private method__
            {static}- void setError(Text warnText, TextArea errorText, ProgressIndicator indicator, boolean loading, Exception e)
        }

        class github.weichware10.analyse.gui.general.LoginController {
            - TextField benutzernameId
            - PasswordField passwortId
            - TextField schemaId
            - Text warnText
            - TextArea errorText
            - ProgressIndicator indicator
            __private methods__
            - void loginOnEnter(KeyEvent keyEvent)
            - void loginToDatabase()
            - void closeProgramm()
            __protected method__
            # void initialize()
        }

        class github.weichware10.analyse.gui.general.MainMenuBar {
            {static}- MenuBar root
            __public method__
            {static}+ MenuBar getMenuBar()
            __protected methods__
            {static}# void openDocs()
            {static}# void changeDataBaseUrl()
            {static}# void resetDataBaseUrl()
        }

        class github.weichware10.analyse.gui.general.MainMenuBarController {
            - MenuItem logOutMenu
            - MenuItem logsMenu
            __public method__
            + void openDocumentation()
            __private method__
            - void setLogOutDisable(ObservableBooleanValue obs)
            __protected methods__
            # void logOut()
            # void resetDataBaseUrl()
            # void setDataBaseUrl()
            # void toggleLogs()
            # void setLogText(ObservableBooleanValue visible)
            # void initialize()
        }

    }
}
' Interaktionen admin
github.weichware10.analyse.gui.admin.Configurator o-- github.weichware10.analyse.gui.admin.ConfiguratorController
github.weichware10.analyse.gui.admin.StringsDialog o-- github.weichware10.analyse.gui.admin.StringsDialogController
github.weichware10.analyse.gui.admin.TrialCreator o-- github.weichware10.analyse.gui.admin.TrialCreatorController

' Interaktionen analyse
github.weichware10.analyse.gui.analyse.Analyzer o-- github.weichware10.analyse.gui.analyse.AnalyzerController
github.weichware10.analyse.gui.analyse.DiagramConfigurator o-- github.weichware10.analyse.gui.analyse.DiagramConfiguratorController
github.weichware10.analyse.gui.analyse.HeatmapConfigurator o-- github.weichware10.analyse.gui.analyse.HeatmapConfiguratorController
github.weichware10.analyse.gui.analyse.TrialSelector o-- github.weichware10.analyse.gui.analyse.TrialSelectorController

' Interaktionen general
github.weichware10.analyse.gui.general.Login o-- github.weichware10.analyse.gui.general.LoginController
github.weichware10.analyse.gui.general.MainMenuBar o-- github.weichware10.analyse.gui.general.MainMenuBarController
github.weichware10.analyse.gui.general.FunctionChooser o-- github.weichware10.analyse.gui.general.FunctionChooserController

class github.weichware10.util.gui.AbsScene
github.weichware10.util.gui.AbsScene <|-- github.weichware10.analyse.gui.admin.Configurator
class github.weichware10.util.gui.AbsSceneController
github.weichware10.util.gui.AbsSceneController <|-- github.weichware10.analyse.gui.admin.ConfiguratorController
class javafx.scene.control.Dialog
javafx.scene.control.Dialog <|-- github.weichware10.analyse.gui.admin.StringsDialog
github.weichware10.util.gui.AbsSceneController <|-l- github.weichware10.analyse.gui.admin.StringsDialogController
github.weichware10.util.gui.AbsScene <|-- github.weichware10.analyse.gui.admin.TrialCreator
github.weichware10.util.gui.AbsSceneController <|-l- github.weichware10.analyse.gui.admin.TrialCreatorController
github.weichware10.util.gui.AbsScene <|-- github.weichware10.analyse.gui.analyse.Analyzer
github.weichware10.util.gui.AbsSceneController <|-l- github.weichware10.analyse.gui.analyse.AnalyzerController
github.weichware10.util.gui.AbsScene <|-- github.weichware10.analyse.gui.analyse.DiagramConfigurator
github.weichware10.util.gui.AbsSceneController <|-l- github.weichware10.analyse.gui.analyse.DiagramConfiguratorController
github.weichware10.util.gui.AbsScene <|-- github.weichware10.analyse.gui.analyse.HeatmapConfigurator
github.weichware10.util.gui.AbsSceneController <|-l- github.weichware10.analyse.gui.analyse.HeatmapConfiguratorController
github.weichware10.util.gui.AbsScene <|-- github.weichware10.analyse.gui.analyse.TrialSelector
github.weichware10.util.gui.AbsSceneController <|-l- github.weichware10.analyse.gui.analyse.TrialSelectorController
github.weichware10.util.gui.AbsScene <|-- github.weichware10.analyse.gui.general.FunctionChooser
github.weichware10.util.gui.AbsSceneController <|-l- github.weichware10.analyse.gui.general.FunctionChooserController
github.weichware10.util.gui.AbsScene <|-- github.weichware10.analyse.gui.general.Login
github.weichware10.util.gui.AbsSceneController <|-l- github.weichware10.analyse.gui.general.LoginController
github.weichware10.util.gui.AbsScene <|-- github.weichware10.analyse.gui.general.MainMenuBar
github.weichware10.util.gui.AbsSceneController <|-l- github.weichware10.analyse.gui.general.MainMenuBarController

@enduml