@startuml codecharts
skinparam defaultTextAlignment center

actor       Nutzer          as n
entity      System          as s    #DA70D5
collections GUI             as g

box CodeCharts

participant CodeCharts              as cc
participant CodeChartsController    as ct
participant CodeChartsCoordinator   as co
participant CodeChartsInput         as ci
participant CodeChartsPane          as cp
end box

collections configClient          as c

activate n
activate s
activate g

== Initialisierung ==
g -> cc : new CodeCharts(primaryStage, configClient, dataBaseClient)
activate cc
cc -> c : getConfig()
note left : auslesen und verarbieten der Konfiguration
activate c
c --> cc : Data
note left : new TrailData 
deactivate c
cc -> co : new CodeChartsCoordinator([...])
activate co
co -> ci : new CodeChartsInput()
co -> c : getConfig()
activate c
c --> co : Data
deactivate c
co -> cp : new CodeChartsPane([...])
deactivate co

== Test ==
loop
    cc -> co : iterate()
    deactivate cc
    activate co
    co -> g : Aufruf Bild, Raster und Eingabe
    co -> ci : getInput(currentStrings, currentIteration, iterations)
    activate ci
    ci --> co : Data
    deactivate ci
end

== Ende == 
co -> cc : endTest()
deactivate co
activate cc
cc -> g : End(primaryStage, configClient, dataBaseClient, trialData)
deactivate cc

@enduml
