@startuml github.weichware10.toolbox.zoommaps
title github.weichware10.toolbox.zoommaps

package github.weichware10.toolbox.zoommaps {

    ' -=- classes (github.weichware10.toolbox.zoommaps) -=-
    class github.weichware10.toolbox.zoommaps.ZoomCalculator {
        ' --- values (github.weichware10.toolbox.zoommaps.ZoomCalculator) ---

        ' --- fields (github.weichware10.toolbox.zoommaps.ZoomCalculator) ---
        - double speed
        - TrialData data
        ~ ConfigClient configClient
        ~ ZoomMapsController controller
        ~ ZoomImage zoomImage
        ~ String question
        ~ String imageUrl

        ' --- methods (github.weichware10.toolbox.zoommaps.ZoomCalculator) ---
        +  ZoomCalculator(TrialData data, ConfigClient configClient, ZoomMapsController controller)
        + void processInput(Point2D raw, int direction)
    }

    class github.weichware10.toolbox.zoommaps.ZoomImage {
        ' --- values (github.weichware10.toolbox.zoommaps.ZoomImage) ---

        ' --- fields (github.weichware10.toolbox.zoommaps.ZoomImage) ---
        + double[] imageSize
        - ImageView imageView

        ' --- methods (github.weichware10.toolbox.zoommaps.ZoomImage) ---
        +  ZoomImage(String location, ImageView imageView, ZoomCalculator zoomCalculator)
        + Point2D getImageCoordinates(Point2D imageViewCoordinates)
        # Rectangle2D move(Point2D position, double speed)
        - double clamp(double value, double min, double max)
    }

    class github.weichware10.toolbox.zoommaps.ZoomInput {
        ' --- values (github.weichware10.toolbox.zoommaps.ZoomInput) ---

        ' --- fields (github.weichware10.toolbox.zoommaps.ZoomInput) ---
        ~ ZoomCalculator zoomCalculator

        ' --- methods (github.weichware10.toolbox.zoommaps.ZoomInput) ---
        +  ZoomInput(ZoomCalculator zoomCalculator)
        + void handle(InputEvent event)
        - void handleClick(MouseEvent mouseEvent)
        + void handleScroll(ScrollEvent scrollEvent)
    }

    class github.weichware10.toolbox.zoommaps.ZoomMaps {
        ' --- values (github.weichware10.toolbox.zoommaps.ZoomMaps) ---

        ' --- fields (github.weichware10.toolbox.zoommaps.ZoomMaps) ---
        - Stage primaryStage
        - DataBaseClient dataBaseClient
        - TrialData trialData
        - ConfigClient configClient
        ~ ZoomMapsController controller

        ' --- methods (github.weichware10.toolbox.zoommaps.ZoomMaps) ---
        +  ZoomMaps(Stage primaryStage, ConfigClient configClient, DataBaseClient dataBaseClient)
        + void endTest(String answer)
    }

    class github.weichware10.toolbox.zoommaps.ZoomMapsController {
        ' --- values (github.weichware10.toolbox.zoommaps.ZoomMapsController) ---

        ' --- fields (github.weichware10.toolbox.zoommaps.ZoomMapsController) ---
        - ResourceBundle resources
        - URL location
        - TextField answerField
        - ImageView imageView
        - Label questionLabel
        - Button submitButton
        - Text warnText
        - ZoomMaps zoomMaps

        ' --- methods (github.weichware10.toolbox.zoommaps.ZoomMapsController) ---
        + ImageView getImageView()
        + void setImageViewSize(double width, double height)
        + void setImage(Image image)
        + void setQuestion(String question)
        + void setZoomMaps(ZoomMaps zoomMaps)
        + void setWarn(String warn)
        ~ void endTestOnEnter(KeyEvent event)
        ~ void endTest()
        ~ void initialize()
    }

}

' autogenerated field links, may be faulty.
github.weichware10.toolbox.zoommaps.ZoomCalculator o-- github.weichware10.toolbox.zoommaps.ZoomMapsController
github.weichware10.toolbox.zoommaps.ZoomCalculator o-- github.weichware10.toolbox.zoommaps.ZoomImage
github.weichware10.toolbox.zoommaps.ZoomInput o-- github.weichware10.toolbox.zoommaps.ZoomCalculator
github.weichware10.toolbox.zoommaps.ZoomMaps o-- github.weichware10.toolbox.zoommaps.ZoomMapsController
github.weichware10.toolbox.zoommaps.ZoomMapsController o-- github.weichware10.toolbox.zoommaps.ZoomMaps

' autogenerated inheritances, may be faulty.
interface javafx.event.EventHandler
javafx.event.EventHandler <|.. github.weichware10.toolbox.zoommaps.ZoomInput

@enduml