@startuml zoommaps
state "Fehler" as err : informative Fehlermeldung
state Speichern : der Daten in der Datenbank

state "Tutorial" as t {
    state "Abfrage von Config" as ac : getConfigState()\nSoll Tutorial angezeigt werden?
    state "Tutorial anzeigen" as ta
    [*] --> ac
    ac --> ta : Ja
    ac --> p : Nein
    ta --> p
}

state "PreTest" as p {
    state "Abfrage Intro Text" as it : getConfigState()\nWas ist der Intro Inhalt ?
    state "Intro anzeigen" as ia
    [*] --> it
    it --> ia
    ia --> s
}

state "Setup" as s {
    state "Konfiguration abfragen" as ka : speed, image location, imageViewWidth, imageViewHeight, Question
    state "Vorbereitung Bild" as vb : instanziieren und anzeigen
    [*] --> ka
    ka --> vb : Konfiguration erhalten
    ka -d-> err : Konfiguration nicht erhalten
    vb -l-> v
}

state "Versuch" as v {
    state "Auf Benutzerinput warten" as bi : Scrollen und Klicken
    state "Berechnung Bildposition" as bb : aus ImageView Koordinaten
    state "Anpassung Bildposition" as ab : Dauer hängt von speed ab
    state "Abspeichern neuer Position" as ap
    [*] --> bi
    bi --> bb : Input
    bb --> ab
    ab --> ap
    ap --> bi
    ap -u-> Speichern : Versuch beendet
}

[*] --> t
Speichern -u-> [*]
err -d-> [*]

@enduml
