@startuml zoommaps
skinparam defaultTextAlignment center

actor       Nutzer          as n
entity      System          as s    #DA70D5
collections GUI             as g

box ZoomMaps

participant ZoomMaps        as zm
participant ZoomCalculator  as zc
participant ZoomImage       as zb
participant ZoomInput       as zi
end box

participant configClient    as c
participant TrialData       as td

activate n
activate s
activate g

== Initialisierung ==
g -> zm : new ZoomMaps(primaryStage, configClient, dataBaseClient)
activate zm

zm -> td : new TrialData
activate td
note left: TrialData Objekt zum Abspeichern der Ergebnisse
deactivate c

zm -> zc : new ZoomCalculator(trialData, configClient, controller)
activate zc
zc -> c : getConfig()
activate c
c --> zc : Konfiguration
deactivate c
zc -> zb : new ZoomImage(imageUrl, ImageView, this)
activate zb
zb -> zi : new ZoomInput(zoomCalculator)
activate zi

== Test ==
loop
    n -> s : Scrollen bzw. Klicken
    s -> zi : Event
    zi -> zc : processInput(Point2D, direction)
    zc -> zb : getImageCoordinates(raw)
    zb --> zc : Point2D
    zc -> zb : move(img, direction * speed)
    zb -> zc : viewport
    zc -> td : addDataPoint(viewport)

end

== Ende ==
deactivate zb
deactivate zi
deactivate zc
g -> zm : endTest(String answer)
td --> zm : erhobene Daten
deactivate td
zm -> g : End(primaryStage, configClient, dataBaseClient, trialData)
deactivate zm

@enduml
