@startuml zoommaps
skinparam defaultTextAlignment center


actor       Nutzer          as n
entity      System          as s    #DA70D5
collections GUI             as g

box ZoomMaps

participant ZoomMaps        as zm
participant ZoomCalculator  as zc
participant ZoomImage       as zb
participant ZoomInput       as zi
end box

collections configClient          as c

activate n
activate s
activate g

== Initialisierung ==
g -> zm : ZoomMaps(primaryStage, configClient, dataBaseClient)
activate zm
zm -> c : getTrailData()
activate c
c --> zm : trialData : TrailData
deactivate c

zm -> zc : ZoomCalculator(trialData, configClient, controller)
deactivate zm
activate zc
zc -> c : getData()
activate c
c --> zc : imageUrl, question, speed
deactivate c
zc -> zb : ZoomImage(imageUrl, ImageView, this)
deactivate zc
activate zb
zb -> zi : ZoomInput(zoomCalculator)
deactivate zb
activate zi

== Test ==
loop
    n -> s : Scrollen bzw. Klicken
    s -> zi : Event
    zi -> zc : processInput(Point2D, direction)
    activate zc
    zc -> zb : getImageCoordinbates(raw)
    activate zb
    zb --> zc : Point2D
    deactivate zb
    zc -> zb : move(img, direction * speed)
    activate zb
    zb -> zc : viewport
    deactivate zb
    deactivate zc

end

== Ende == 
g -> zm : endTest(String answer)
activate zm
zm -> g : End(primaryStage, configClient, dataBaseClient, trialData)
deactivate zm

@enduml
