@startuml zoommaps
left to right direction

actor Testperson as t
actor Forschende as f

rectangle ZoomMaps as z #789dd5 {
    usecase "Tutorial anschauen" as td
    usecase "Bild betrachten" as bb
    usecase "Antwort abgeben" as aa
    usecase ba as "Bildausschnitt anpassen
    ..
    Klicken & Scrollen"
    bb .l.> ba : <<include>>
}

rectangle Config as c {
    usecase "Einstellungen setzen" as es
}

rectangle Analyse as a {
    usecase "Ergebnisse anschauen" as ea
}

' Testperson
t -- td
t -- bb
t -- ba
t -- aa

' Forschende
es -- f
ea -- f

' intern
z ..> a : über Datenbank / JSON
z <.. c : Versuchseinstellungen

@enduml
