@startuml github.weichware10.util.gui
title github.weichware10.util.gui

package github.weichware10.util.gui {

    ' -=- classes (github.weichware10.util.gui) -=-
    class github.weichware10.util.gui.AbsScene {
        ' --- values (github.weichware10.util.gui.AbsScene) ---

        ' --- methods (github.weichware10.util.gui.AbsScene) ---
        {static}+ InitResult initialize(URL fxml)
        {static}+ void setMenuBar(MenuBar menuBar, Parent root)
        {static}+ InitResult start(Stage primaryStage, URL fxml, Parent root, AbsSceneController controller, String title, MenuBar menuBar, Integer width, Integer height, String icon)
    }
    class github.weichware10.util.gui.AbsScene$InitResult {
        ' --- values (github.weichware10.util.gui.AbsScene$InitResult) ---

        ' --- fields (github.weichware10.util.gui.AbsScene$InitResult) ---
        + Parent root
        + AbsSceneController controller

        ' --- methods (github.weichware10.util.gui.AbsScene$InitResult) ---
        #  InitResult(Parent root, AbsSceneController controller)
    }
    github.weichware10.util.gui.AbsScene +-- github.weichware10.util.gui.AbsScene$InitResult

    class github.weichware10.util.gui.AbsSceneController {
        ' --- values (github.weichware10.util.gui.AbsSceneController) ---

        ' --- fields (github.weichware10.util.gui.AbsSceneController) ---
        # ResourceBundle resources
        # URL location

        ' --- methods (github.weichware10.util.gui.AbsSceneController) ---
        {abstract}# void initialize()
    }

    class github.weichware10.util.gui.Log {
        ' --- values (github.weichware10.util.gui.Log) ---

        ' --- fields (github.weichware10.util.gui.Log) ---
        {static}- Stage logStage
        {static}- Parent root
        {static}- SimpleBooleanProperty visibleProperty
        {static}+ ObservableBooleanValue visible

        ' --- methods (github.weichware10.util.gui.Log) ---
        {static}+ void start(String icon)
        {static}+ boolean isVisible()
        {static}+ void show()
        {static}+ void hide()
        {static}+ void close()
        {static}+ void log(String content, String type)
    }

    class github.weichware10.util.gui.LogController {
        ' --- values (github.weichware10.util.gui.LogController) ---

        ' --- fields (github.weichware10.util.gui.LogController) ---
        - ResourceBundle resources
        - URL location
        - TextField logInput
        - TextArea logArea
        - Pane logPane
        - MenuButton logMenuButton

        ' --- methods (github.weichware10.util.gui.LogController) ---
        # void initialize()
        ~ void setLogType(ActionEvent event)
        ~ void inputKeyPress(KeyEvent event)
        ~ void log()
    }

}

' autogenerated field links, may be faulty.
github.weichware10.util.gui.AbsScene$InitResult o-- github.weichware10.util.gui.AbsSceneController

' autogenerated inheritances, may be faulty.
github.weichware10.util.gui.AbsScene <|-- github.weichware10.util.gui.Log
github.weichware10.util.gui.AbsSceneController <|-- github.weichware10.util.gui.LogController

github.weichware10.util.gui.Log .. github.weichware10.util.gui.LogController : Verbindung über Bindings

@enduml
