name: Dokumentation Weichware 10
markdown: GFM
# JUST THE DOCS
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
logo: "https://avatars.githubusercontent.com/u/92639923"

# remote_theme: karloespiritu/BlackDoc
# remote_theme: Wiredcraft/carte

