@startuml util

' Externe Packages
package Toolbox {}
note left of Toolbox: beinhaltet alle Tools
package AnalyseClient {}

package Util {
    ' --- TUTORIAL ---
    abstract Tutorial<t: ToolType> {
      - toolType: ToolType
      - configClient: ConfigClient
      __public method__
      + Tutorial(configClient: ConfigClient,toolType: ToolType)
      + start() : void
      __private methods__
      - getConfigState() : boolean
      - setConfigState(state: boolean) : void
      - show() : boolean
      __abstract methods__
      - {abstract} tutorial() : void
    }

    enum ToolType {
        ZOOM
        EYETRACKING
        CODECHARTS
    }

    ' --- BILD ---

    abstract Bild {
        # location : String
        + Bild(url: String)
        + show() : void
        + hide() : void
    }

    class Data<t: ToolType> {
        + tooltype: ToolType
        + configId: int
        + data: unknown
    }

    package Config {
        class ConfigClient {
            - configuration : Configuration
            + getConfig() : Configuration
            + loadConfiguration() : boolean
        }
        class ConfigLoader {
            + loadConfiguration(location: String) : Configuration
        }
        class ConfigWriter {
            + writeConfiguration(location: String, configuration: Configuration) : boolean
        }
        class ConfigGui {
            # configState: Configuration
            + showEditor() : void
        }
        class Configuration {
            - tools : ToolType[0..3]
            - saveLocation : String
            - codeChartsConfiguration : CodeChartsConfiguration
            - eyeTrackingConfiguration : EyetrackingConfiguration
            - zoomMapsConfiguration : ZoomMapsConfiguration
            __public methods__
            + getTools() : ToolType[0..3]
            + getSaveLocation() : String
            + getCodeChartsConfiguration() : CodeChartsConfiguration
            + getEyeTrackingConfiguration() : EyeTrackingConfiguration
            + getZoomMapsConfiguration() : ZoomMapsConfiguration
            __private methods__
            - checkToolInput(tools: ToolType[*])
        }
        class CodeChartsConfiguration {
            - strings : String[*]
            - initialSize : float
            - timings : float[2]
            + getStrings(): String[]
            + getInitialSize(): float
            + getTimings(): float[]
        }
        class EyetrackingConfiguration {
            - pollIntervall : float
            + getPollIntervall() : float
        }
        class ZoomMapsConfiguration {
            - speed : float
            + getSpeed() : float
        }
        abstract ToolConfiguration {
            - imageUrl : String
            - tutorial : boolean
            + getImageUrl() : String
            + getTutorial() : boolean
            + setTutorial(boolean tutorial) : void
        }

        ' ConfigClient ..> Configuration

        ConfigClient o-d- ConfigLoader : < lädt Konfiguration

        ConfigClient o-d- ConfigWriter : < schreibt Konfiguration

        ConfigClient -l- ConfigGui : < Konfigurationsbearbeitung

        Configuration ..> ZoomMapsConfiguration
        Configuration ..> CodeChartsConfiguration
        Configuration ..> EyetrackingConfiguration

        ZoomMapsConfiguration --|> ToolConfiguration
        CodeChartsConfiguration --|> ToolConfiguration
        EyetrackingConfiguration --|> ToolConfiguration
    }

    package Speichermedium {
        ' SpeicherUtilities
        class SpeicherUtilities {
            - Location: String
            + SpeicherUtilities(location: String)
            + getLocation() : String
            + setLocation(location: String) : boolean
            + deleteData(inputString: String) : boolean
            + searchData(inputString: String) : Data
            + saveData(inputData: Data) : boolean
        }

    }

    ' Interaktionen
    Tutorial -- ToolType
    Data -- ToolType
    Tutorial -r- Config
    ConfigClient -r- Speichermedium

}
' Externe Module
ConfigClient -u- Toolbox
SpeicherUtilities -- Toolbox : < Data
SpeicherUtilities -- AnalyseClient : > Data

@enduml
