name: puml-to-img
on:
  push:
    paths: ['docs/.java/**']
jobs:

  doctomd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout weichware10/dokumente
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WEICHBOT }}
      - name: clone repositories
        run: |
          mkdir .temp
          cd .temp
          git clone https://github.com/weichware10/util
          git clone https://github.com/weichware10/toolbox
          git clone https://github.com/weichware10/analyse
          cd ..
      - run: tree
